{{ if .Values.pgbouncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    component: pgbouncer
spec:
  replicas: {{ .Values.pgbouncer.replicaCount }}
  updateStrategy:
    {{- toYaml .Values.pgbouncer.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
      component: pgbouncer
  template:
    metadata:
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
        component: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: "{{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}"
          imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy | quote }}
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "-h"
                - "localhost"
                - "-U"
                - "postgres"
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
            - name: PGHOST
              value: 127.0.0.1
            - name: PGUSERFILE
              value: "/etc/secrets/postgresql/superuser/username"
            - name: PGPASSWORDFILE
              value: "/etc/secrets/postgresql/superuser/password"
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: superuser
              mountPath: /etc/secrets/postgresql/superuser
          resources:
            {{- toYaml .Values.pgbouncer.resources | nindent 12 }}
      {{- with .Values.pgbouncer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.pgbouncer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.pgbouncer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: superuser
          secret:
            secretName: {{ include "postgresql.superuserSecretName" . | quote }}
{{ end }}
