apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  cluster.yaml: |
    {{`# WAL-G backup configuration`}}
    backup:
      {{- if .Values.backup.enabled }}
      {{- with .Values.backup.env }}
      env:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backup.envFrom }}
      envFrom:
        - /etc/wal-g.d/env
      {{- end }}
      {{- with .Values.backup.interval }}
      interval: {{ toYaml . }}
      {{- end }}
      {{- with .Values.backup.retention }}
      retention:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      enabled: false
      {{- end }}
