{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "postgresql.fullname" . }}-patroni
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "postgresql.fullname" . }}-patroni
subjects:
- kind: ServiceAccount
  name: {{ include "postgresql.serviceAccountName" . }}
{{- end -}}
