name: Package Helm Chart

on:
  push:
#    paths:
#      - deploy/charts/**

jobs:

  package:
    name: Package
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Release
      uses: helm/chart-releaser-action@master
      with:
        charts_dir: deploy/charts/k8s-postgresql/
      env:
        CR_TOKEN: ${{ secrets.CR_TOKEN }}
